### ISSUE TITLE
Game crash when in tutorial

### ISSUE THREAD

**Issue by Shtuffs** [eezstreet/SWATEliteForce#465] opened 2019-06-25 22:35 UTC
No Label

Crash Time: 06/25/19 18:30:21

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 1997 MHz with 2047MB RAM
Video: Intel(R) UHD Graphics 620 (6471)

UserName: (My name)
ComputerName: (Name of my laptop)
Application location: C:\Program Files (x86)\GOG Galaxy\Games\SWAT 4\ContentExpansion\System\

SWAT Build Number: 7.0

Access Violation caused General protection fault!

History: UPepperSprayCameraEffect::PostRender <- FPlayerSceneNode::Render <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop->GenerateExtraCrashInfo [(GLevel: 'myLevel' PendingLevel: '(NULL)' NetMode: 'NM_Standalone'] <- MainLoop

**Comment by eezstreet** [comment] 2020-05-25 21:37
Verified.

**Comment by eezstreet** [comment] 2021-02-28 03:26
This is a duplicate of #537 and that issue has been fixed.

**Closed by eezstreet** 2021-02-28 03:26 UTC
Labels: Singleplayer, Verified
