### ISSUE TITLE
[BUG] skin error

### ISSUE THREAD

**Issue by Eskalar** [eezstreet/SWATEliteForce#548] opened 2020-08-24 07:08 UTC
The weapon my brother is holding is incorrectly displayed on the screen
https://youtu.be/VD3XylNHMwg
https://youtu.be/XC0bzU6X6T4

**Comment by eezstreet** [comment] 2021-03-10 20:45
Duplicate of #513.

**Closed by eezstreet** 2021-03-10 20:45 UTC
