### ISSUE TITLE
Classic menu behavior

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#106] opened 2017-04-05 04:52 UTC
After issuing a command in a nested submenu (e.g. "investigate") the command menu should immediately return to the top level. The player is unlikely to issue multiple commands in the same nested submenu back-to-back; for example, after a "breach and clear", your next command probably isn't going to be another breaching command; it is much more likely to be "fall in", "restrain", or "use taser/pepper spray/etc". Hitting backspace to close the submenu is clumsy.

**Comment by theengineertcr** [comment] 2017-04-05 10:38
I have spoken to eez about this before but he has said that this is unlikely to happen(difficulty may be faced when implementing submenus blue red and element). However, coding this in is very simple. I will be giving out my version of the CommandInterface in the SEF Discord channel soon if you would like to try it.

**Comment by eezstreet** [comment] 2017-04-06 23:24
This is a duplicate of an existing issue: #81

**Closed by eezstreet** 2017-04-06 23:24 UTC

**Comment by theengineertcr** [comment] 2017-05-01 23:13
This is for you Kevin, check it out and tell me what you think:
PlayerInterface_Command_SP: http://puu.sh/vCzSK/0b10f9f83c.ini
CommandInterfaceMenus_SP: http://puu.sh/vCzTe/fcc3fd8f63.ini
Video of this: https://www.youtube.com/watch?v=aI4UCeOUBao
