### ISSUE TITLE
All missions won't appear in alphabetical order sometimes(when using an all mission career)

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#226] opened 2017-05-23 05:24 UTC
Happens usually when entering the career for the first time, then playing a mission, then reentering it.

**Comment by kevinfoley** [comment] 2017-05-23 08:01
Duplicate of #218

**Comment by theengineertcr** [comment] 2017-05-23 08:27
Didn't see the alphabetical order check there, my bad.

**Closed** 2017-05-23 11:24 UTC
