### ISSUE TITLE
Suspects who spot you will sometimes run and shoot towards your direction without line of sight

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#292] opened 2017-07-29 22:10 UTC
If a suspect spots you, starts shooting at you and moving, as they go through every room they will keep firing towards you, behind millions of walls, hitting every civi that gets in his way, etc.

**Comment by sandman332** [comment] 2017-07-29 23:08
I can confirm this issue..  I think suspects need to check if they can actually hit the target while fleeing, because I have seen times where a suspect has fleed half way around the map and I am looking through one of the sniper units and I see a suspect running backwards shooting at walls and anything and everything that gets in his way.  Sucks a lot of the time when they kill hostages because of it.

**Comment by sandman332** [comment] 2017-08-05 01:59
This should be fixed.  Suspects are not aloud to attack while fleeing if they can not hit the target anymore.

**Closed** 2017-08-05 06:28 UTC
